#almalinux is same as rhel so using it and rehel is licensed and charagable so is using almalinux
#FROM to start with base Img because any instance or img we need OS. so using bare min OS
FROM almalinux:9