#Label are used while filtering the images or multiple set of data
#author we can use as below in the label. Earlier we have maintainer instruction where we can give all our
# author, artifacts but it's deprecated and can be used as Label only

FROM almalinux:9
LABEL COURSE="DevOps" \
      TRAINER="Johnson" \
      DURATION="120HRS" \
      com.joindevops.dockerfile.author="John@gamil.com"
